[package]
name = "jamiw1/musiccontrol"
description = "a package giving you a native-like music display and controls, with tons of customizability and ease of use."
version = "2.1.0"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/jamiw1/MusicControl"
realm = "shared"
license = "MIT"
authors = ["jamied <hey@isuckat.dev>"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.2.4"
goodsignal = "stravant/goodsignal@0.3.0"